[project]
name = "fastapi-app"
version = "0.1.0"
description = "A CRUD backend app using fastapi"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard,stander]>=0.128.0",
    "pytest>=9.0.2",
    "requests>=2.32.5",
]
